### ISSUE TITLE
今天突然scan错误，直到昨天都好好的

### ISSUE THREAD

**Issue by MysteryManTK** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#133]
看来，但我不确定我真的很明白，因为我确实有很多看不懂的地方

看了，我的理解是连接到civitai的网站请求超时，但我不确定

今天想scan一下新的模型，发现一直都是错误，然后去控台看一下，有看到Civitai Helper: Request model info from civitai，然后等了一会就出一段代码，但是我真的看不太懂，勉强能看懂最后的timed out 应该是超时了，不过我想知道的是，这个是纯网络代理造成的还是因为其他原因造成的，因为如果是纯代理原因，从更新至1.6.1.1后我已经正常使用很久了，我想确认一下，所以我希望能通过控制台帮我排查一下原因，本人这方面纯小白希望可以讲的通俗易懂一些，非常谢谢

##
![uTools_1682755799179](https://user-images.githubusercontent.com/132129804/235292209-a1b2a844-2f5b-415d-b5ba-26ba3969880a.png)

## 
![uTools_1682755725733](https://user-images.githubusercontent.com/132129804/235292219-0a4df1ff-3fc3-4dce-b78a-bd1169035a26.png)

**Comment by GGQZ** [comment]
我也是一模一样的错误
我认为代理应该没什么问题 开的全局代理 也能正常上c站
![image](https://user-images.githubusercontent.com/132135215/235296749-3c202c35-c111-4d41-b7d4-7cc104d33b35.png)

**Comment by GJFVNPA** [comment]
和我一样的原因我的也是无法更新了不知道出了什么问题

**Comment by kangyx00** [comment]
一样，无法更新
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/model-versions/by-hash/5493a0ec491f5961dbdc1c861404088a6ae9bd4007f6a3a7c5dee8789cdc1361 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001DBE0FE48B0>, 'Connection to civitai.com timed out. (connect timeout=None)'))

**Comment by ZL1417896412** [comment]
我也是这个问题，但是当我开启了clash的tun模式之后就可以正常使用了，可能简单的系统代理会出错，要用虚拟网卡才行？
希望作者大大可以更新一下，解决这个问题，之前仅仅是系统代理就可以正常用了

**Comment by GJFVNPA** [comment]
> 我也是这个问题，但是当我开启了clash的tun模式之后就可以正常使用了，可能简单的系统代理会出错，要用虚拟网卡才行？ 希望作者大大可以更新一下，解决这个问题，之前仅仅是系统代理就可以正常用了

我试了一下还是没法更新啊。。。。

**Comment by Kepler-16b** [comment]
bump

**Comment by wangnimaaa** [comment]
我还以为只有我出问题了，代理我都换了几个还是一样，只能等作者修复了，这插件是真的好用啊！

**Comment by wangnimaaa** [comment]
作者千万别弃坑啊！！

**Comment by yuyu363** [comment]
我也碰到了一模一样控制台的报错，无法扫描添加预览图。我尝试了各种方法，重启，重装插件，全局代理（我的浏览器是一直都能打打开c站的，c站没有崩）。持续了两天了，一直连不上，扫描的时候报错

**Comment by butaixianran** [comment]
我这边没有任何问题。

插件界面上有填写代理的地方，填入代理。你的浏览器能访问civitai不等于你的python能访问civitai。

挂了代理还不行，那就是你的代理或者civitai的问题了。过段时间再试。

**Comment by MysteryManTK** [comment]
哇，它行了，它行了，虽然其实我不太能听不懂作者你的回答的一些内容，但是我通过chatGPT的帮助和你的回答要点相结合，通过尝试更改代理可以了，感谢作者的回答，太激动了

**Comment by heijuanmao67** [comment]
> 哇，它行了，它行了，虽然其实我不太能听不懂作者你的回答的一些内容，但是我通过chatGPT的帮助和你的回答要点相结合，通过尝试更改代理可以了，感谢作者的回答，太激动了

你好，可以请问一下具体是如何解决的吗？作为纯粹的外行想查相关的知识都有些难以下手。具体来问的话，要如何找到自己vpn的代理服务器地址?是以http://地址:端口 的格式填进去就可以了吗？

**Comment by MysteryManTK** [comment]
> > 哇，它行了，它行了，虽然其实我不太能听不懂作者你的回答的一些内容，但是我通过chatGPT的帮助和你的回答要点相结合，通过尝试更改代理可以了，感谢作者的回答，太激动了
> 
> 你好，可以请问一下具体是如何解决的吗？作为纯粹的外行想查相关的知识都有些难以下手。具体来问的话，要如何找到自己vpn的代理服务器地址?是以[http://地址:端口](http://%E5%9C%B0%E5%9D%80:%E7%AB%AF%E5%8F%A3) 的格式填进去就可以了吗？

这，我只能说，我在我的代理那边找到了一个参数 叫做 HTTP：xxxxx，但是我不清楚你的代理是什么样的，然后就想你说的一样，就是那个格式，地址话就是sd网页的那个地址保留：前面的内容，然后+上http显示的参数的数字，然后保存完要全部关掉再重开，我的就可以了

**Comment by heijuanmao67** [comment]
> 

仍然没有成功，但还是谢谢你，我再学一下是怎么回事

**Comment by MysteryManTK** [comment]
> > 
> 
> 仍然没有成功，但还是谢谢你，我再学一下是怎么回事

嗯，你再试试把，我也试了很多次，我是按它的格式format: http://127.0.0.1:port → 在输入框 → http://127.0.0.1:xxxxx ，也有可能和它文档里说的那个”有些sock5代理, 需要使用socks5h开头的形式"socks5h://xxxxx"才能生效。“，因为我的代理里面 还有一个叫 SOCKS:XXXXX 的参数，反正 这两个格式我都试了 我成功了第一个

**Comment by linpeichu** [comment]
打开windows设置-网络和Internet-代理，检查自己的手动设置代理，地址和端口
复制地址和端口，例如http://127.0.0.1:7890
到C站助手的最下端，保存，记得重启webui才能生效

**Comment by heijuanmao67** [comment]
> 打开windows设置-网络和Internet-代理，检查自己的手动设置代理，地址和端口 复制地址和端口，例如http://127.0.0.1:7890 到C站助手的最下端，保存，记得重启webui才能生效

谢谢，成功了

**Comment by anne43983959** [comment]
解决方案如图所示，最好不要去开clash的全局代理或者tun模式，很有可能和gradio内置队列冲突，导致右上角出现页面报错
![QQ截图20230430124213](https://user-images.githubusercontent.com/115604775/235335876-65a3428b-9532-48ee-b473-55495ade14b3.png)

**Comment by kiou21** [comment]
看前几楼的过程瞎搞了一整子，弄好了。(打开加速器,手动设置代理自己会打开)
也不知道是不是我网络问题
![屏幕截图 2023-04-30 215610](https://user-images.githubusercontent.com/129520430/235356980-5fbc897b-b466-4bfd-b755-c838bcd17587.png)

**Comment by kangyx00** [comment]
哈，我也这样开代理弄了一下，是可以了，不过新问题是没有出现那四个图标，就算是点刷新边上的小按钮也没有出现。你们正常？



在 2023-04-30 22:03:06，"kiou21" ***@***.***> 写道：

看前几楼的过程瞎搞了一整子，弄好了。(打开加速器,手动设置代理自己会打开)
也不知道是不是我网络问题

**Comment by SilverLeaffs** [comment]
感谢各位，终于成功了。。
原来需要在c站助手最下面的代理加上代理资料。。

**Comment by xinmi501505** [comment]
> 看前几楼的过程瞎搞了一个整子，弄好了。(打开加速器，手动设置代理自己会打开) 也不知道是不是我网络问题 ![屏幕截图 2023-04-30 215610](https://user-images.githubusercontent.com/129520430/235356980-5fbc897b-b466-4bfd-b755-c838bcd17587.png)

可以了用这方法~

**Comment by QQ804218** [comment]
代理中的地址.工具可以自动读取系统信息并填写吗?如有问题用户可自行修改...

**Comment by FAu001** [comment]
clash打开局域网共享开关，填入局域网地址与端口填入插件最下面那一栏即可使用了

**Comment by hakuroba** [comment]
谢谢楼上各位

**Comment by silverhero888** [comment]
it's work! thanks.

**Comment by 50889492** [comment]
按照你们上面的内容修改了今天又报错了！
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\AI\novelai-webui-aki-v3\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 84, in scan_model
    civitai.get_preview_image_by_model_path(item, max_size_preview, skip_nsfw_preview)
  File "G:\AI\novelai-webui-aki-v3\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 359, in get_preview_image_by_model_path
    util.download_file(img_url, sec_preview)
  File "G:\AI\novelai-webui-aki-v3\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\util.py", line 52, in download_file
    r = requests.get(url, stream=True, headers=def_headers, proxies=proxies)
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "G:\AI\novelai-webui-aki-v3\py310\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='imagecache.civitai.com', port=443): Max retries exceeded with url: /xG1nkqKTMzGDvpLrqFT7WA/9f30bd75-f46f-4aac-a992-b2dd0d427200/width=450/326873.jpeg (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000260A88C61A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

**Comment by silverhero888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我已收到邮件，谢谢！

**Comment by LanceGao97** [comment]
> 打开windows设置-网络和Internet-代理，检查自己的手动设置代理，地址和端口 复制地址和端口，例如http://127.0.0.1:7890 到C站助手的最下端，保存，记得重启webui才能生效

http://127.0.0.1:7890/     

Thanks it works， 
建议作者把设置代理这一条 放在  Install 安装说明了，  我直到看到这个帖子 才明白怎么用这个插件。 否则  scan后一直是error。

**Comment by yuyu363** [comment]
非常感谢你的解答！！！很有用，立马帮我解决了问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月7日(周日) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] 今天突然scan错误，直到昨天都好好的 (Issue #133)




  
打开windows设置-网络和Internet-代理，检查自己的手动设置代理，地址和端口 复制地址和端口，例如http://127.0.0.1:7890 到C站助手的最下端，保存，记得重启webui才能生效
  
http://127.0.0.1:7890/
 
Thanks it works，
 建议作者把设置代理这一条 放在  Install 安装说明了，  我直到看到这个帖子 才明白怎么用这个插件。 否则  scan后一直是error。

**Comment by 350640267** [comment]
我也是，求大大解答怎么搞，已经在下面填写http://127.0.0.1:7890/了

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\sd-webui-aki-v4\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 66, in scan_model
    model_info = civitai.get_model_info_by_hash(hash)
  File "E:\sd-webui-aki-v4\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 47, in get_model_info_by_hash
    r = requests.get(url_dict["hash"]+hash, headers=util.def_headers, proxies=util.proxies)
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\sd-webui-aki-v4\py310\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/model-versions/by-hash/f253abb016c22dd426d6e482f4f8c3960766de6e4c02f151478bfb98f6985383 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C012D31AB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

**Comment by xymlx** [comment]
这个问题好久了，我之前一直以为是civitai那边的问题，今天才想起来看一下，成功按照各位的方法解决，非常感谢！

**Comment by xymlx** [comment]
这个问题好久了，我之前一直以为是civitai那边的问题，今天才想起来看一下，成功按照各位的方法解决，非常感谢！

**Comment by better319** [comment]
> 我这边没有任何问题。
> 
> 插件界面上有填写代理的地方，填入代理。你的浏览器能访问civitai不等于你的python能访问civitai。
> 
> 挂了代理还不行，那就是你的代理或者civitai的问题了。过段时间再试。

我用的是秋叶的版本，谁能截个图给我看下，他是怎么设置的，秋叶的启动项里面要设置吗？代理

**Comment by better319** [comment]
vpn 全局代理+网页civitai助手页最下面http://127.0.0.1:7890/

**Comment by better319** [comment]
vpn 全局代理+网页civitai助手页最下面http://127.0.0.1:7890/


启动器代理上面也填上http://127.0.0.1:7890/

**Comment by QuietyAwe** [comment]
> 打开windows设置-网络和Internet-代理，检查自己的手动设置代理，地址和端口 复制地址和端口，例如http://127.0.0.1:7890 到C站助手的最下端，保存，记得重启webui才能生效

thx,it works

**Comment by soldier-xinqch** [comment]
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/10648552/3344d7f3-e091-4d9b-83f3-411601f7c730)

**Comment by Justlove-dk** [comment]
我开了VPN之后，到win10的设置-网络和Internet-代理这个界面上看不到代理地址信息和端口啊，我的都是空着的

**Comment by ccwctv** [comment]
> 打开windows设置-网络和Internet-代理，检查自己的手动设置代理，地址和端口 复制地址和端口，例如http://127.0.0.1:7890 到C站助手的最下端，保存，记得重启webui才能生效

请问软路由的怎么解决
passwall翻墙的，Windows不开代理软件

**Comment by Luvsummer** [comment]
用的clash for windows的vpn 把System Proxy勾上再去scan，亲测成功

**Comment by silverhero888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我已收到邮件，谢谢！

**Comment by AimerSo** [comment]
遇到这个问题了，总结一下自己的解决过程，我并没有使用到Windows设置，所以可能不适用于所有人：

1.打开Web UI之前先用魔法
2.找到你魔法的代理设置，你可能会发现 (https_proxy=http://127.0.0.1:xxxxx) 或 (all_proxy=socks5://127.0.0.1:xxxxx)
3.打开Web UI，点击Civita助手（Civita Helper），下拉找到Civitai的代理设置，把https_proxy或all_proxy后面网址填入
4.填入后保存，重启UI即可
5.还是错误，开摆！（不是，那我就不知道咋整了

我先尝试加载https_proxy，还是超时，用了all_proxy(socks5）全局就可以了，本质上还是因为civitai被墙，需要设置才可用

**Comment by butaixianran** [comment]
文档写了有些代理需要填写socks5h开头的，不是http开头。

**Comment by silverhero888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我已收到邮件，谢谢！

**Comment by XhnPLayer** [comment]
Clash for windows 我全开了,才成功连上,能下载图片了.  虚拟网卡 TAP 服务模式 TUN模式  全开.  用的规则代理.  可以了.

**Comment by 717qwq** [comment]
整好了，在设置中填好代理后记得重启!重启!重启!重启!重启!

**Comment by silverhero888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我已收到邮件，谢谢！

**Comment by onlydx** [comment]
页面上没有找到设置代理的地方，是版本更新了吗？

**Comment by silverhero888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我已收到邮件，谢谢！

**Comment by cooper1x** [comment]
> clash打开局域网共享开关，填入局域网地址与端口填入插件最下面那一栏即可使用了

还是不行

**Comment by silverhero888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我已收到邮件，谢谢！

**Comment by Daozi756** [comment]
> vpn 全局代理+网页civitai助手页最下面http://127.0.0.1:7890/
> 
> 启动器代理上面也填上http://127.0.0.1:7890/
牛逼我的哥

**Comment by silverhero888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我已收到邮件，谢谢！
