### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by DarksealStudios** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#149]
Civitai: Check resources for missing preview images
Startup time: 22.0s (load scripts: 3.1s, reload script modules: 0.3s, list SD models: 1.0s, create ui: 17.0s, gradio launch: 0.6s).
Civitai: Found 672 resources missing preview images
Civitai: Found 1 hash matches
Civitai: Updated 0 preview images
Traceback (most recent call last):
  File "F:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "F:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
Traceback (most recent call last):
  File "F:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "F:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

**Comment by DarksealStudios** [comment]
sorry, updated, ok now.

**Comment by butaixianran** [comment]
This is not an error of this extension. Do not claim other extension's error to this one.
