### ISSUE TITLE
扫描不了新加的模型，也不能下载模型

### ISSUE THREAD

**Issue by chen135347542093** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#173]
Traceback (most recent call last):
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 66, in scan_model
    model_info = civitai.get_model_info_by_hash(hash)
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 47, in get_model_info_by_hash
    r = requests.get(url_dict["hash"]+hash, headers=util.def_headers, proxies=util.proxies)
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "E:\AI\01-01HH\novelai-webui-aki-v3A\py310\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/104272971/1a1ede9d-f3ad-42ab-95e2-c1fd0d293191)

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
