### ISSUE TITLE
Error message when using Scan on Civitai Helper

### ISSUE THREAD

**Issue by Spaceisprettybig** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#193]
## I get an unfamiliar error message and error when using civitai helper. It seems to also hinder the ability to use it again without restarting Automatic1111

![Screenshot (710)](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/120803420/a14386b6-1c0f-4e3e-843c-925144b11e11)

## Traceback (most recent call last):
  File "E:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Ai\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Ai\Automatic1111\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 58, in scan_model
    hash = util.gen_file_sha256(item)
  File "E:\Ai\Automatic1111\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\util.py", line 37, in gen_file_sha256
    for block in read_chunks(f, size=blocksize):
  File "E:\Ai\Automatic1111\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\util.py", line 25, in read_chunks
    chunk = file.read(size)
PermissionError: [Errno 13] Permission denied

**Comment by comsomgenik** [comment]
删除lora子文件后，好了

**Comment by songib** [comment]
@comsomgenik deleting which one?

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
