### ISSUE TITLE
Maintain backwards compatibility with 1.5

### ISSUE THREAD

**Issue by VL4DST3R** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#250]
## Have you read document?
yes

## Have you checked console log window's msg?
yes

## Describe Issue
This is in regards to the notice (and confirming that indeed does no longer work for webui 1.5):
"This extension request latest SD webui v1.6.x, update it before using this extension.)"

1.6 Comes with all kinds of issues with other extensions and I'd rather not be forced to use it just yet. I kindly ask you to consider maintaining backwards compatibility with 1.5 like other extensions are doing (e.g. dynamic thresholding prompting you are using a legacy version of the ui but still working regardless) so people like me and my group of friends can still use this great extension.
## Console log's msg or screenshot for function issue
```
Traceback (most recent call last):
  File "S:\system\python\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\system\python\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "S:\system\python\lib\site-packages\gradio\blocks.py", line 1251, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "S:\system\python\lib\site-packages\gradio\blocks.py", line 423, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "S:\system\python\lib\site-packages\gradio\blocks.py", line 308, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: Textbox.update() got an unexpected keyword argument 'info'
```

**Comment by butaixianran** [comment]
hi, it won't go back for 1.5 any more. sorry for that
