### ISSUE TITLE
H11错误，不能正常下载和更新模型信息

### ISSUE THREAD

**Issue by Eyn-C** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#257]
之前没问题的，最近打开更新了下发现有问题，已经几天了

部分错误信息：
...
Civitai Helper: This image is NSFW: Soft
ERROR:asyncio:Exception in callback H11Protocol.timeout_keep_alive_handler()
handle: <TimerHandle when=5255.203 H11Protocol.timeout_keep_alive_handler()>
Traceback (most recent call last):
  File "H:\Stable Diffusion\python\lib\site-packages\h11\_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>
...
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "H:\Stable Diffusion\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "H:\Stable Diffusion\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 383, in timeout_keep_alive_handler
    self.conn.send(event)
...
*** API error: POST: http://127.0.0.1:7860/api/predict {'error': 'LocalProtocolError', 'detail': '', 'body': '', 'errors': "Can't send data when our state is ERROR"}
...
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "H:\Stable Diffusion\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
...
  raise LocalProtocolError("Can't send data when our state is ERROR")
h11._util.LocalProtocolError: Can't send data when our state is ERROR
'AsyncRequest' object has no attribute '_json_response_data'

**Comment by Eyn-C** [comment]
补充一下，我的设置是下载所有级别的图片，并没有禁止NSFW内容下载，因为这个错误像是利用h11模块进行图片筛选出的错，所以我强调一下这个，个人家里的电脑自己用，没必要限制

**Comment by Eyn-C** [comment]
我把插件删除掉然后重新安装就可以了，问题已经解决，这个帖子我就不删了留给同样踩坑的：老版本插件里有些东西好像和新版有冲突，重新安装后，设置界面和使用界面都和我原来从老版更新上来的有所不同。

**Comment by butaixianran** [comment]
你的报错中，没有任何部分和本扩展有关。本扩展完全不使用异步请求，你这是其他东西报错。请自行查明原因。
