### ISSUE TITLE
error after updates

### ISSUE THREAD

**Issue by psdsam-NiuNiuKing** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#282]
updates to the new version and get the following error

![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/154928863/29e7a6c5-68b5-4fee-90c4-e332f5a9844c)

Civitai Helper: Searching local model by version id
Civitai Helper: folder: G:\My Drive\sd\stable-diffusion-webui\models\Lora\
Civitai Helper: version_id: 409705
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/409705?type=Training%20Data
Civitai Helper: Target file path: G:\My Drive\sd\stable-diffusion-webui\models\Lora\utaha-kasumigaoka-ponyxl-lora-nochekaiser.zip
Traceback (most recent call last):
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\Users\sp947\stable-diffusion-webui 2\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 796, in dl_model_by_input
    for result in download_files(filename, folder, ver_info, headers, filetypes, dl_all, duplicate):
  File "C:\Users\sp947\stable-diffusion-webui 2\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 635, in download_files
    for result in downloader.dl_file(
  File "C:\Users\sp947\stable-diffusion-webui 2\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\downloader.py", line 337, in dl_file
    total_size = int(response.headers['Content-Length'])
                     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\sp947\stable-diffusion-webui 2\venv\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'content-length'

**Comment by butaixianran** [comment]
hi, you are not using this extension. You are using another fork of this project. 

The extension you installed is from github account "zixaphir". You should ask your question there.

https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

**Comment by psdsam-NiuNiuKing** [comment]
Thank you. Switch to your version now but the get API error: 

To create a public link, set `share=True` in `launch()`.
Startup time: 3.8s (list SD models: 1.9s, load scripts: 0.8s, create ui: 0.9s).
Civitai Helper: Getting model info by: https://civitai.com/models/366604/eriri-spencer-kashiwagi-eri-sawamura-saekano-how-to-raise-a-boring-girlfriend-saenai-heroine-no-sodatekata
Civitai Helper: Run get_model_id_from_url
Civitai Helper: Request model info from civitai
Civitai Helper: Get subfolder for: G:\My Drive\sd\stable-diffusion-webui\models\Lora
Civitai Helper: Get following info for downloading:
Civitai Helper: model_name:Eriri Spencer "Kashiwagi Eri" Sawamura (澤村・スペンサー・英梨々) - Saekano: How to Raise a Boring Girlfriend (Saenai Heroine no Sodatekata) (冴えない彼女〈ヒロイン〉の育てかた)
Civitai Helper: model_type:lora
Civitai Helper: subfolders:['/']
Civitai Helper: version_strs:['booru_409669']
Civitai Helper: subfolder string is None
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/409669
Civitai Helper: This model requires an API key to download. More info: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper#civitai-api-key
Civitai Helper: Downloading failed, check console log for detail


I am pretty sure that my setting is consistent with what you required: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper#civitai-api-key...

**Comment by butaixianran** [comment]
Have you checked the "Content Control" setting in document:
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper#content-setting-of-civitai
