### ISSUE TITLE
Can't get it to work anymore

### ISSUE THREAD

**Issue by gynoidneko** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#300]
This was working great for me earlier, using A1111 Forge. But recently (possibly after a forge update?) it just stopped working.
When I try to get a I get an error that says:

`TypeError: cannot pickle '_thread.lock' object`

It also gives me a bunch of errors like this:

`File "copy.py", line 172, in deepcopy     
  File "copy.py", line 271, in _reconstruct     
  File "copy.py", line 146, in deepcopy     
  File "copy.py", line 231, in _deepcopy_dict     
  File "copy.py", line 161, in deepcopy`

I am using A111 Forge version: [f1.0.2v1.10.1-previous-151-gb7878058](https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/b7878058f9144201924cf983e64d08174cf1756e)  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  gradio: 4.40.0

When I look in the documentation, it mentioned socks5h. I don't know what that is or how it works. I don't have a VPN on right now, in case that is interfering. I tried to put something in the Civitai Helper Proxy setting, but no matter what I put I get error messages. If I add a socks5h proxy server, it tells me there isn't one set up.

Again, no idea why it is doing this or what socks5h is (or how to set it up although I rather not if I don't have to). Any help would be greatly appreciated.

**Comment by gynoidneko** [comment]
Here is the full terminal output when I try to "Get Model Info by Civitai URL":

`Civitai Helper: Getting model info by: https://civitai.com/models/614452/xenogears-elements-kelvena?modelVersionId=686885`
`Civitai Helper: Run get_model_id_from_url`
`Civitai Helper: Request model info from civitai`
`Civitai Helper: Get subfolder for: H:\AI\SDXL\SD Forge\webui\models\Lora`
`Civitai Helper: Get following info for downloading:`
`Civitai Helper: model_name:Xenogears - Elements - Kelvena`
`Civitai Helper: model_type:lora`
`Civitai Helper: subfolders:['\\Pony XL', '\\Pony XL\\Character', '\\Pony XL\\Concept', '\\Pony XL\\Style', '\\Pony XL\\Utility', '\\SDXL\\Character', '\\SDXL\\Concept', '\\SDXL\\Style', '\\SDXL\\Utility', '/']`
`Civitai Helper: version_strs:['1.0, pony_686885', 'sd 1.5_697810']`
`Traceback (most recent call last):`
`  File "H:\AI\SDXL\SD Forge\system\python\lib\site-packages\gradio\queueing.py", line 600, in process_events
    output = copy.deepcopy(response)`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 206, in _deepcopy_list`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 206, in _deepcopy_list`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 206, in _deepcopy_list`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 206, in _deepcopy_list`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 206, in _deepcopy_list`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 206, in _deepcopy_list`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 206, in _deepcopy_list`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 172, in deepcopy`
`  File "copy.py", line 271, in _reconstruct`
`  File "copy.py", line 146, in deepcopy`
`  File "copy.py", line 231, in _deepcopy_dict`
`  File "copy.py", line 161, in deepcopy`
`TypeError: cannot pickle '_thread.lock' object`

**Comment by butaixianran** [comment]
This is not an error of this extension. Your error shows it happens when using "deepcopy" from a copy.py file.  

This extension has no such file, and there is no function called "deepcopy". 

You could be using a fork of this project which has the same extension name.

**Comment by Leayal** [comment]
This is because the breaking changes in APIs from Gradio 3 to Gradio 4.
I think this has a relation to [this issue](https://github.com/gradio-app/gradio/issues/7412).

@gynoidneko If you are using [WebUI from AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui), then I think this extension should still work fine, as this original WebUI is still using Gradio 3. However, Forge recently got a major overhaul and upgrade to use Gradio 4, called `New Forge`.

If it's possible, you can try this extension on [old release before "New Forge" initialized](https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/tag/previous), which is still with Gradio 3.

**Comment by gynoidneko** [comment]
Not a fork, I downloaded it straight from this page. I tried several versions and all give the same thing.
I am using Forge so I will look into either going to an old version of forge or just dropping forge and going with A1111 again. I'll let you know if it works.

**Comment by gynoidneko** [comment]
Yes, https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/pull/124 fixes the problem!
I highly recommend using this fork!

**Comment by Adzido** [comment]
> Yes, [zixaphir#124](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/pull/124) fixes the problem! I highly recommend using this fork!

Sorry I am newbie on gh, how can i download fixed version of this? Cuz I have errors all the time with this exte.

**Comment by a3nima** [comment]
> > Yes, [zixaphir#124](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/pull/124) fixes the problem! I highly recommend using this fork!
> 
> Sorry I am newbie on gh, how can i download fixed version of this? Cuz I have errors all the time with this exte.

in the extensions tab you can enter the github link to install the extension.
