### ISSUE TITLE
Missing dependencies for SOCKS support.

### ISSUE THREAD

**Issue by Omg-ciTy** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#302]
我用的是【socks5h://127.0.0.1:8838】  直接出错   用Proxifier 劫持代理也不行

Civitai Helper: Request model info from civitai
Traceback (most recent call last):
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 99, in scan_model
    return model_action_civitai.scan_model(scan_model_types, max_size_preview, skip_nsfw_preview)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 66, in scan_model
    model_info = civitai.get_model_info_by_hash(hash)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 47, in get_model_info_by_hash
    r = requests.get(url_dict["hash"]+hash, headers=util.def_headers, proxies=util.proxies)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\requests\adapters.py", line 633, in send
    conn = self.get_connection_with_tls_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\requests\adapters.py", line 483, in get_connection_with_tls_context
    proxy_manager = self.proxy_manager_for(proxy)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\requests\adapters.py", line 282, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
                                          ^^^^^^^^^^^^^^^^^^
  File "X:\sd-webui-aki-v4.4\sd-webui-aki-v4.2\python\Lib\site-packages\requests\adapters.py", line 64, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")

requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

**Comment by butaixianran** [comment]
如果你搜索你的出错提示："python Missing dependencies for SOCKS"，就会看到，你的sd webui的python环境中，缺少一个叫pysocks的包，所以不能用socks。  

你可以手动装一下，在类似dos的命令行界面，进入sd webui目录下的"venv\Scripts"子目录。运行命令`activate`。

然后安装这个包：`pip install pysocks` 或者 `pip install "requests[socks]"`  

成功后退出环境：`deactivate`  

全程在sd webui关闭的情况下操作。完成后再启动sd webui。

**Comment by butaixianran** [comment]
测试了一下，新装的sd webui，好像都不再自带pysocks了。比较老版本的sd webui一路升级过来的，是可以直接用socks的。无法确定发生变化的精确版本号。  

已经在插件添加`install.py`，在sd webui启动时，将自动检查pysocks并进行安装。有相同问题的，可升级本扩展到最新版。

**Comment by Omg-ciTy** [comment]
牛的大佬
