### ISSUE TITLE
CIVITAI Url pointing on every item to http://127.0.0.1:7860/

### ISSUE THREAD

**Issue by vampireprincess** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#305]
I have two issues and one suggestion. My suggestion (or question) is: how can I stop the program from updating the preview images when I already have my own preview images, which I prefer over the official ones?

I am using the latest stable version of Stable Diffusion WebUI-Automation (v1.10.1).

**Issue 1:**
The CIVITAI URL on every single item is pointing to http://127.0.0.1:7860/ instead of the actual CIVITAI item URLs.
![Screenshot_1](https://github.com/user-attachments/assets/801796cd-6e46-4ca8-b068-99f6a4894515)

**Issue 2:**
The "Get model info from CIVITAI" function works fine, but the model download is not working, especially when I select a model version from the dropdown. It gives me the following error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Stable Diffusion\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Stable Diffusion\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\Stable Diffusion\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Stable Diffusion\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Stable Diffusion\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\Stable Diffusion\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\Stable Diffusion\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\Stable Diffusion\webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 108, in dl_model_by_input
    return model_action_civitai.dl_model_by_input(dl_model_info, dl_model_type_txtbox, dl_subfolder_drop, dl_version_drop, dl_all_ckb, max_size_preview, skip_nsfw_preview)
  File "F:\Stable Diffusion\webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 484, in dl_model_by_input
    filepath = downloader.dl(url, model_folder, None, None)
  File "F:\Stable Diffusion\webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\downloader.py", line 34, in dl
    rh = requests.get(url, stream=True, verify=False, headers=util.def_headers, proxies=util.proxies)
  File "F:\Stable Diffusion\system\python\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "F:\Stable Diffusion\system\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\Stable Diffusion\system\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\Stable Diffusion\system\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "F:\Stable Diffusion\system\python\lib\site-packages\requests\adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/download/models/216689 (Caused by SSLError(SSLError(58, '[ASN1] nested asn1 error (_ssl.c:4004)')))

```

**Comment by butaixianran** [comment]
For issue1, it doesn't matter how that link shows, everything will be handled in script, not by that link.   

Which is: when you clicking that global icon button, python side will parse the right url for you and send that civitai url to your page, then your webpage's javascript will open it in a new webpage tab. 

For issue 2: 
You log shows you are downloading this model: "Warhammer 40K Commissar Outfit - by EDG". I have tried it, all work fine.  

You log shows a "SSLError", which caused by "[ASN1] nested asn1 error". 
That's not an error of this extension. You need to check your network and your python:  

* Can you connnect to civitai without a proxy? Or, are you using a proxy with this extension? If so, check your proxy. 
* 
* Search "SSLError [ASN1] nested asn1 error" in google. 
* 
* There is some versions of python or conda, have an issue/bug on CA certificates. You may try something like this:
https://github.com/Sygil-Dev/sygil-webui/discussions/1325  

Or, try another version of python or conda. My python version for sd webui is 3.10.6. And I don't use conda, I use mamba, which is a c++ version of conda.  

For other reasons you can not download a model, check following part of the document.

* [Civitai API Key](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper?tab=readme-ov-file#civitai-api-key)
* [Content Setting of Civitai](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper?tab=readme-ov-file#content-setting-of-civitai)
* [Get Wrong model info and preview images from civitai](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper?tab=readme-ov-file#get-wrong-model-info-and-preview-images-from-civitai)

**Comment by vampireprincess** [comment]
Thanks a lot, when I loaded the Stable Diffusion from Opera it worked perfectly, I was able even to download a model after I added the API key.
