### ISSUE TITLE
Cant download any model

### ISSUE THREAD

**Issue by harryxd-x** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#312]
## Have you read document?
yes
## Have you checked console log window's msg?
yes
## Describe Issue
Everytime download model in Stable Diffusion will error 

## Screenshot for UI issue
![image](https://github.com/user-attachments/assets/54949a64-dce6-4b4c-a8d3-7dd58c8db582)

## Console log's msg or screenshot for function issue

> 

> CHv1.8.10: Run get_model_id_from_url
CHv1.8.10: url or model id can not be empty
CHv1.8.10: failed to parse model id from url:
CHv1.8.10: Run get_model_id_from_url
CHv1.8.10: url or model id can not be empty
CHv1.8.10: failed to parse model id from url:
CHv1.8.10: Searching local model by version id
CHv1.8.10: folder: E:\AI\stable-diffusion-webui\stable-diffusion-webui\models\Stable-diffusion\
CHv1.8.10: model_ids: {'model': 827184, 'version': 1068947}
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\ch_lib\model_action_civitai.py", line 823, in dl_model_by_input
    for result in download_files(filename, folder, ver_info, headers, filetypes, dl_all, duplicate):
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\ch_lib\model_action_civitai.py", line 632, in download_files
    dl_info = parse_file_info(ver_info, filename)
  File "E:\AI\stable-diffusion-webui\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\ch_lib\model_action_civitai.py", line 586, in parse_file_info
    filetype = file_info["type"]
KeyError: 'type'

**Comment by butaixianran** [comment]
hi, you are not using this extension, you could be using another fork of this project, which may still be using the same extension name. 

Your error is on line 586 with `filetype = file_info["type"]`.

This extension doesn't have this line in its code. Also, code file "model_action_civitai.py" only have 512 lines, there is no line 586.

**Comment by harryxd-x** [comment]
thx i can download after i download the correct version :>
