### ISSUE TITLE
backend.args error

### ISSUE THREAD

**Issue by hotick** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#313]
It is the latest version of the plugin, which was originally running normally. 
One day, the following error suddenly appeared. I recall that there were no other changes or additions/removals of other plugins.
I have already added the “backend“ package, but the error still persists.

*** Error loading script: image_metadata.py
    Traceback (most recent call last):
      File "F:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "frozen importlib._bootstrap_external", line 883, in exec_module
      File "frozen importlib._bootstrap", line 241, in _call_with_frames_removed
      File "F:\AI\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\image_metadata.py", line 10, in <module>
        from backend.args import dynamic_args
    ModuleNotFoundError: No module named 'backend.args'

---

**Comment by butaixianran** [comment]
You are not using this extension, you are using another fork of this project which has the same extension name.  

Your error is on a file "image_metadata.py", this extension does not have that file.

**Comment by hotick** [comment]
oh，understand。thank you
WebUI default URL have this error

https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui-extensions/master/index.json
