### ISSUE TITLE
Scanning models crashes Google Colab

### ISSUE THREAD

**Issue by alpkabac** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#34]
Google Colab crashes while scanning because RAM usage spikes. I tested if this was a model specific issue and it was not. Here is the crash log although I don't know what might provide. 

`Civitai Helper: Calculate SHA256
Civitai Helper: Using Memory Optimized SHA256
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/lib/util.py", line 18, in gen_file_sha256
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/lib/util.py", line 18, in <lambda>
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/lib/model_action_civitai.py", line 34, in scan_model
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/scripts/lib/util.py", line 19, in gen_file_sha256
OSError: [Errno 107] Transport endpoint is not connected
Interrupted with signal 2 in <frame at 0xe1091450, file '/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py', line 150, code sigint_handler>
`

**Comment by alpkabac** [comment]
Something interesting happened. It managed to hash the previosly erroring model but gave an error on the next one. I can't understand what is the problem. Any help would be appreciated.

**Comment by butaixianran** [comment]
Are you using the latest v1.4 version? In that case, memory optimized sha256 is already used.

If you are still having a memory issue, then there is nothing I can do anymore.

The only solution is buy a paid account, which will double your memory in corlab
