### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by biship** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#41]
I just updated to 520128ac (Sun Mar 12 15:38:57 2023).
It has been working fine since release, until I updated today.
I last updated Stable-Diffusion-Webui-Civitai-Helper on 3/11/23 and whatever that version was worked fine.

```
Restarting UI...
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\Downloads\apps\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Error executing callback ui_tabs_callback for D:\Downloads\apps\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py
Traceback (most recent call last):
  File "D:\Downloads\apps\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\Downloads\apps\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 72, in on_ui_tabs
    always_display = setting.data["general"]["always_display"]
KeyError: 'always_display'

Running on local URL:  http://127.0.0.1:7860
```

**Comment by butaixianran** [comment]
Shut down SD web ui and re-launch. Just Reload UI won't work. Document already said that.

**Comment by biship** [comment]
Fixed!

**Comment by butaixianran** [comment]
Reopen it as a tutorial, to prevent other user open the same issue.
