### ISSUE TITLE
Max retries exceeded

### ISSUE THREAD

**Issue by anitman** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#73]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue

After Scanning or check versions, I got this error with several day. It looks like the api key have been restricted.

Civitai Helper: Start scan_model
Civitai Helper: Scanning path: E:\git\stable-diffusion-webui\embeddings
Civitai Helper: Scanning path: E:\git\stable-diffusion-webui\models\hypernetworks
Civitai Helper: Scanning path: E:\git\stable-diffusion-webui\models\Stable-diffusion
Civitai Helper: Checking preview image for model: E:\git\stable-diffusion-webui\models\Stable-diffusion\768-v-ema.ckpt
Civitai Helper: Model Info is empty
Civitai Helper: Checking preview image for model: E:\git\stable-diffusion-webui\models\Stable-diffusion\AbyssOrangeMix2_hard.safetensors
Civitai Helper: Model Info is empty
Civitai Helper: Creating model info for: Ade_NFmix.ckpt
Civitai Helper: Use Memory Optimized SHA256
Civitai Helper: sha256: 6067bbd7827279730e844a6b55cf3e359eab582d9639b0223ad6a81542c198ea
Civitai Helper: length: 2836718166
Civitai Helper: Request model info from civitai
Traceback (most recent call last):
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\linke\.conda\envs\py310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000192B3475B70>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/model-versions/by-hash/6067bbd7827279730e844a6b55cf3e359eab582d9639b0223ad6a81542c198ea (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000192B3475B70>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\git\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 66, in scan_model
    model_info = civitai.get_model_info_by_hash(hash)
  File "E:\git\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 46, in get_model_info_by_hash
    r = requests.get(url_dict["hash"]+hash, headers=util.def_headers, proxies=util.proxies)
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\git\stable-diffusion-webui\venv\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/model-versions/by-hash/6067bbd7827279730e844a6b55cf3e359eab582d9639b0223ad6a81542c198ea (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000192B3475B70>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

**Comment by anitman** [comment]
It seems that the plugin can't recognize and generate accurate info data of some models and continue sending queries which cause the code stop functioning.

**Comment by butaixianran** [comment]
This is your Internet issuue, you cannot connect to civitai API service.

Set a proxy if civitai is blocked by your Internet provider's firewall

**Comment by LiJT** [comment]
Same error, I think Civitai has changed some Policy to prevent massive request?

**Comment by butaixianran** [comment]
I just tested, there is no any issue when using proxy. Again, if your Internet provider blocked your connection to civitai API service, use a proxy.

**Comment by chrme** [comment]
Their servers were down at that time. Check official discord.

**Comment by butaixianran** [comment]
This extension will delay 1 second after sending request to civitai, so civitai won't block it at all.  

There is no policy changed. Civitai already has a request pool, which will set the total request's number it can accept at same time. This setting has been there from a long time. So no need to change any policy any more.  

Also, If civitai refused a request, then will be error code and error msg from civitai, not "Max retries exceeded". This means you can't event connect to its server.

If you are using proxy and connection still doesn't work, either your porxy is down or civitai is down.

**Comment by anitman** [comment]
@butaixianran problem solved
