### ISSUE TITLE
Error loading script ... ImportError: cannot import name 'model' from 'scripts.ch_lib' (unknown location)`

### ISSUE THREAD

**Issue by ride5k** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#90]
`Error loading script: civitai_helper.py
Traceback (most recent call last):
  File "T:\auto1111\stable-diffusion-webui-directml\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "T:\auto1111\stable-diffusion-webui-directml\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "T:\auto1111\stable-diffusion-webui-directml\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py", line 20, in <module>
    from scripts.ch_lib import model
ImportError: cannot import name 'model' from 'scripts.ch_lib' (unknown location)`

**Comment by butaixianran** [comment]
I guess you update it from a very old version and did not re-launched SD webui.

Document said it very clearly, stop sd webui and re-launch it after updating.

**Comment by ride5k** [comment]
with all due respect, that is not the issue.  machine has been cold booted multiple times, problem persists.  extensions updated via command line, not webui gui.

**Comment by butaixianran** [comment]
Closed since no reply
